# render.yaml
staticSites:
  - name: gaspass-frontend
    # on lui dit de lancer les commandes DANS client/
    rootDir: client
    env: node
    buildCommand: |
      npm ci
      npm run build
    publishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: DB_HOST
        fromSecret: DB_HOST
      - key: DB_PORT
        fromSecret: DB_PORT
      - key: DB_USER
        fromSecret: DB_USER
      - key: DB_PASS
        fromSecret: DB_PASS
      - key: DB_NAME
        fromSecret: DB_NAME
