# render.yaml
staticSites:
  - name: ecommerce-frontend
    env: node
    # npm run build lancera d’abord generate:data puis react-scripts build
    buildCommand: |
      npm ci
      npm run build
    publishPath: build          # ou "dist" si Vite
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: DB_HOST
        fromSecret: DB_HOST
      - key: DB_PORT
        fromSecret: DB_PORT
      - key: DB_USER
        fromSecret: DB_USER
      - key: DB_PASS
        fromSecret: DB_PASS
      - key: DB_NAME
        fromSecret: DB_NAME
